plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.3.21'
    id "com.github.ben-manes.versions" version "0.54.0"
    id 'maven-publish'
}

group = 'responsible'
version = '1.0.4'

repositories {
    mavenCentral()
}

dependencies {
    api(
        "org.openapi4j:openapi-operation-validator:1.0.7",
    )

    implementation(platform("io.vertx:vertx-stack-depchain:5.1.1"))
    api(
        "io.vertx:vertx-lang-kotlin-coroutines",
        "io.vertx:vertx-web-client",
        'io.vertx:vertx-openapi',
    )

    testImplementation 'org.jetbrains.kotlin:kotlin-test'
}

test {
    useJUnitPlatform()
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinJvmCompile).configureEach {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11
        allWarningsAsErrors.set(true)
    }
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}

dependencyUpdates {
    checkConstraints = true

    rejectVersionIf {
        final version = it.candidate.version.toLowerCase()

        [
            "m", // milestone
            "alpha",
            "beta",
            "eap",
            "rc",
            "cr",
        ].any { version.contains(it) }
    }
}
